package api.migration.addressing.entities.addons

import api.addressing.fixed.entities.AddressingDevice
import api.migration.original.entites.addons.DynamicGatewayConnectionModuleLaunchingDevice

interface DynamicGatewayConnectionModuleLaunchingAddressingDevice: DynamicGatewayConnectionModuleLaunchingDevice, AddressingDevice