package api.accesspoint.migration.entities

import api.accesspoint.original.entities.AccessPoint
import api.migration.original.entites.MigrationSupportingDevice

interface MigrationSupportingAccessPoint: AccessPoint, MigrationSupportingDevice