package addons.accesspoint.addressing.entities

import api.accesspoint.original.entities.AccessPoint
import api.addressing.dynamic.consumer.entities.DynamicAddressingNotificationConsumerDevice

interface AddressingAccessPoint: DynamicAddressingNotificationConsumerDevice, AccessPoint