package api.common

enum class Events(val tag: Int) {
    NETWORK_DEVICE_ADDRESS_TUPLE(6000),
    NETWORK_DEVICE_ADDRESS_TUPLE_FREE_LINK(6001),
    DYNAMIC_GATEWAY_CONNECTION_DEVICE_NEW_PARENT_ID(6002),
    MOBILE_DEVICE_NEXT_MOVE(6003),
    ACCESS_POINT_CONNECTED_DEVICE_UPDATE_CONNECTION(6004),
    ADDRESSING_DEVICE_CREATE_CHILDREN_MAPPING(6005),
    NOTIFICATION_CONSUMER_WAIT_PRODUCERS(6006),
    NOTIFICATION_PRODUCER_WAIT_NOTIFICATION(6007),
    NOTIFICATION_CONSUMER_NOTIFY(6008),
    ADDRESSING_DEVICE_ADDRESS_TUPLE(6009),
    MIGRATION_SUPPORTING_DEVICE_MIGRATION_DECISION(6010),
    MIGRATION_SUPPORTING_DEVICE_MIGRATION_PREPARE(6011),
    MIGRATION_SUPPORTING_DEVICE_MIGRATION_START(6012),
    MIGRATION_SUPPORTING_DEVICE_MODULE_DEPARTED(6013),
    MIGRATION_SUPPORTING_DEVICE_MODULE_ARRIVED(6014),
    MIGRATION_SUPPORTING_DEVICE_REMOVE_MODULE(6015),
    MIGRATION_SUPPORTING_DEVICE_MIGRATE_TUPLES(6016),
    MODULE_ADDRESSING_MIGRATION_SUPPORTING_DEVICE_SUPPRESS_MODULE(6017),
}