package api.common

enum class Events(val tag: Int) {
    NETWORK_DEVICE_ADDRESS_TUPLE(6000),
    DYNAMIC_GATEWAY_CONNECTION_DEVICE_NEW_PARENT_ID(6001),
    MOBILE_DEVICE_NEXT_MOVE(6002),
    ACCESS_POINT_CONNECTED_DEVICE_UPDATE_CONNECTION(6003),
    ADDRESSING_DEVICE_ADDRESS_TUPLE_TO_TARGET_DEVICES(6004),
    NOTIFICATION_CONSUMER_WAIT_PRODUCERS(6005),
    NOTIFICATION_PRODUCER_WAIT_NOTIFICATION(6006),
    NOTIFICATION_CONSUMER_NOTIFY(6007),
}