package addons.accesspoint_addressingdynamic.entities

import api.accesspoint.original.entities.AccessPointConnectedDevice
import addons.addressing_dynamic.producer.entities.DynamicAddressingNotificationProducerDevice

interface AddressingAccessPointConnectedDevice: DynamicAddressingNotificationProducerDevice, AccessPointConnectedDevice