package addons.migration.addressing.behaviors

import api.addressing.fixed.behaviors.AddressingDeviceBehavior
import addons.migration.addressing.entities.DynamicGatewayConnectionModuleLaunchingAddressingDevice
import addons.migration.original.behaviors.DynamicGatewayConnectionModuleLaunchingDeviceBehavior
import api.network.dynamic.behaviors.DynamicGatewayConnectionDeviceBehavior
import api.network.fixed.behaviors.NetworkDeviceBehavior

class DynamicGatewayConnectionModuleLaunchingAddressingDeviceBehaviorImpl(
        override val device: DynamicGatewayConnectionModuleLaunchingAddressingDevice,
        override val superDynamicGatewayConnectionDeviceBehavior: DynamicGatewayConnectionDeviceBehavior<AddressingDeviceBehavior<NetworkDeviceBehavior>>)
    : DynamicGatewayConnectionModuleLaunchingDeviceBehavior<DynamicGatewayConnectionDeviceBehavior<AddressingDeviceBehavior<NetworkDeviceBehavior>>>